### ISSUE TITLE
Problem in converting biom file from Q2 to Bugbase compatible format

### ISSUE THREAD

**Issue by skd217** [mestaki/qiime2-to-BugBase#1]
Hi there, 
Thanks for your tutorial. While following the steps mentioned in your tutorial, I am facing issue during clustering of the sequences at 97% similarity threshold using a closed-reference approach.

I am getting this error:

Plugin error from vsearch:

  Some feature ids are present in table, but not in sequences. The set of features in sequences must be identical to the set of features in table. Feature ids present in table but not sequences are: b901052d2411ea898be450af4a818744, 197807ce20d797d34d428f6de66f7999

See above for debug info.

Kindly help in resolving this issue. 
Thanks !!

**Comment by mestaki** [comment]
Hi @skd217,

Without knowing anything about your process so far, the error suggests that your `table.qza` and the `rep-seq.qza` do not match exactly. Did you by chance do some filtering in your table that you didn't also do with your sequences? If so, you'll want to filter your rep-seqs file too so they are identical, use `qiime feature-table filter-seqs`  to filter your sequences based on those present in your table. Hope that helps!

**Comment by skd217** [comment]
Thank you @mestaki 
Yeah I got it right. The output I got Q2 was named as table.qza and rep-seq.qza instead of table-dada2.qza and rep-seq-dada2.qza, respectively. So I changed the name of files accordingly in the command and finally I got the bugbase compatible file following your tutorial.
